# application-dev.yml
server:
  port: 8080
  address: 0.0.0.0        # bind to all interfaces (LAN)

spring:
  h2:
    console:
      enabled: true
      settings.web-allow-others: false # keep console local-only
management:
  endpoints:
    web:
      exposure:
        include: "health,info"
